[DEFAULT]
# Project settings for vigiapet
project_path = C:\Users\Vinicius Santos\Documents\GitHub\Vigia Pet\BehaveAI-main\projects\vigiapet
clips = C:\Users\Vinicius Santos\Documents\GitHub\Vigia Pet\BehaveAI-main\projects\vigiapet\clips
input = C:\Users\Vinicius Santos\Documents\GitHub\Vigia Pet\BehaveAI-main\projects\vigiapet\input
output = C:\Users\Vinicius Santos\Documents\GitHub\Vigia Pet\BehaveAI-main\projects\vigiapet\output

# GUI defaults
primary_motion_classes = 0
primary_motion_colors = 0
primary_motion_hotkeys = 0
primary_static_classes = 0
primary_static_colors = 0
primary_static_hotkeys = 0

secondary_motion_classes = 0
secondary_motion_colors = 0
secondary_motion_hotkeys = 0
secondary_static_classes = 0
secondary_static_colors = 0
secondary_static_hotkeys = 0

